[color]
width = 640
height = 480
fps = 30
format = "bgr8"

[stereo]
width = 1280
height = 720
fps = 6
enable_depth = true
enable_infra = true
depth_format = "z16"
infra_format = "y8"

[accel]
fps = 0 # 0 means default/max supported

[gyro]
fps = 0
