[color]
width = 640
height = 480
fps = 30
format = "bgr8"

[depth]
width = 1280
height = 720
fps = 6
format = "z16"

[infrared]
width = 1280
height = 720
fps = 6
format = "y8"

[accel]
fps = 0 # 0 means default/max supported

[gyro]
fps = 0
